name: Regression Testing Operator Integration

on:
  workflow_dispatch:

env:
  AGENT_TESTS: java

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Kind cluster and local Docker registry
        run:
           bash test/operator/kind-with-registry.sh

      - name: Create Test Images
        run: |
           for t in ${AGENT_TESTS[@]}
           do
             echo "Creating image for $t"
             docker build -t $t-test-app test/operator/$t
             docker tag $t-test-app localhost:5001/registry/$t-test-app
             docker push localhost:5001/registry/$t-test-app
           done

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.11.2

      - name: Install Operator Skeleton
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml
          bash test/operator/wait_for_pod_start.sh cert-manager cert-manager- 1/1 3
          kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
          bash test/operator/wait_for_pod_start.sh opentelemetry-operator-system opentelemetry-operator-controller-manager 2/2 1
          kubectl get pods -A

      - name: Add Namespaces And Instrumentation Skeleton
        run: |
          kubectl create namespace banana
          kubectl create namespace elastic-otel
          kubectl create -f test/operator/elastic-instrumentation.yml

      - name: Start Test Images
        run: |
          for t in ${AGENT_TESTS[@]}
          do
            echo "Starting pod for $t"
            kubectl create -f test/operator/$t/test-app.yaml
            bash -x test/operator/wait_for_pod_start.sh banana $t-test-app 1/1 1
            kubectl logs $t-test-app -n banana
            kubectl delete -f test/operator/$t/test-app.yaml
            #bash -x test/$t/agent_has_started.sh
          done